first/App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name='App_Blog'

urlpatterns = [
    path('',views.BlogList.as_view(),name="blog_list"),
    path('write/',views.CreateBlog.as_view(),name="create_blog"),
    path('details/<str:slug>',views.blog_details,name="blog_details"),
    path('liked/<pk>/',views.liked,name="liked_post"),
    path('unliked/<pk>/',views.unliked,name="unliked_post"),
    path('my-blogs/',views.MyBlogs.as_view(),name="my_blogs"),
    path('edit/<pk>/',views.UpdateBlog.as_view(),name="edit_blog"),
]

first/App_Login/urls.py
from django.urls import path
from App_Login import views


app_name='App_Login'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login_user,name="login"),
    path('logout/',views.logout_user,name="logout"),
    path('profile/',views.profile,name="profile"),
    path('change-profile/',views.user_change,name="user_change"),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/',views.add_profile_pic,name="profile_change"),
    path('change-picture/',views.change_pro_pic,name="change_pro_pic"),
    ]

first/first/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.index,name="index"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    <title> {% block title_block%} My Blogs {%endblock%}</title>
</head>
<body>
       <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><img src="/media/blog.png" width="50px"></a>
            </li>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    @{{user.username}}</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
                    <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
                    <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
                    <hr>
                    <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Log Out<a>   
                </div>
            </div>
            {% else %} 
            <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'App_Login:login' %}">Log in</a>
            </li>
            {% endif %}    
        </ul>
       </nav>
<div class="container" style="padding-top:20px">
    {%block body_block%}

    {%endblock%}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>